{{/*apiVersion: cert-manager.io/v1*/}}
{{/*kind: Certificate*/}}
{{/*metadata:*/}}
{{/*  name: notifo*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*spec:*/}}
{{/*  dnsNames:*/}}
{{/*    - notifo*/}}
{{/*  secretName: notifo*/}}
{{/*  issuerRef:*/}}
{{/*    name: selfsigned*/}}
{{/*    kind: ClusterIssuer*/}}